version: '3.8'
services:
  registry060:
    image: 'apache/nifi-registry:latest'
    container_name: registry060
    hostname: registry060
    user: root
    ports:
      - "18084:18084"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18084
      - TZ=America/Argentina/Buenos_Aires
      - LANG=es_AR.UTF-8
    volumes:
      - ./flow_storage/:/opt/nifi-registry/nifi-registry-current/flow_storage/
      - ./logs/:/opt/nifi-registry/nifi-registry-current/logs