version: '3.8'
services:
  nifi1114:
    image: 'apache/nifi:1.11.4'
    container_name: nifi1114
    hostname: nifi
    user: root
    ports:
      - "8084:8084"
    environment:
      - NIFI_WEB_HTTP_PORT=8084
      - NIFI_ELECTION_MAX_WAIT=1 min
      - TZ=America/Argentina/Buenos_Aires
      - LANG=es_AR.UTF-8
      - NIFI_JVM_HEAP_MAX=2g
    volumes:
      - ../../Librerias/:/home/nifi/
      - ./Nifi/conf/:/opt/nifi/nifi-1.11.4/conf/    
      - ./Nifi/content_repository/:/opt/nifi/nifi-1.11.4/content_repository/
      - ./Nifi/database_repository/:/opt/nifi/nifi-1.11.4/database_repository/
      - ./Nifi/flowfile_repository/:/opt/nifi/nifi-1.11.4/flowfile_repository/
      - ./Nifi/provenance_repository/:/opt/nifi/nifi-1.11.4/provenance_repository/
      - ./Nifi/logs/:/opt/nifi/nifi-1.11.4/logs/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    networks:
      - elastic
  registry060:
    image: 'apache/nifi-registry:latest'
    container_name: registry060
    hostname: registry060
    user: root
    ports:
      - "18084:18084"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18084
      - TZ=America/Argentina/Buenos_Aires
      - LANG=es_AR.UTF-8
    volumes:
      - ./Registry/flow_storage/:/opt/nifi-registry/nifi-registry-current/flow_storage/
      - ./Registry/logs/:/opt/nifi-registry/nifi-registry-current/logs
    networks:
      - grilon      
  es790:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es790
    environment:      
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./Elasticsearch/logs/:/usr/share/elasticsearch/logs/
    networks:
      - elastic
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
  kibana790:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana790
    ports: 
     - "5601:5601"
    environment:
     - ELASTICSEARCH_HOSTS=http://es790:9200/
    networks:
      - elastic
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M  
  filebeat790:
   image: docker.elastic.co/beats/filebeat:7.9.0
   user: root
   container_name: filebeat790
   environment:
    - ELASTICSEARCH_HOST=$${ELASTICSEARCH_HOST:-es790}
    - KIBANA_HOST=$${KIBANA_HOST:-kibana790}
    - output.elasticsearch.hosts=["es790:9200"]
    - setup.kibana.host=kibana790:5601
   command: ["--strict.perms=false"]
   volumes:
    - ./Filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro    
    - ./Filebeat/data/:/usr/share/filebeat/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    - /var/log/:/var/log/:ro
    - /var/log/audit/:/var/log/audit/:ro    
   networks:
    - elastic 
   deploy:
    mode: global
    restart_policy:
     condition: on-failure     
     max_attempts: 3
networks:
  elastic:
    driver: bridge