version: '3.8'
services:
  nifi1170:
    image: 'apache/nifi:1.17.0'
    container_name: nifi1170
    hostname: nifi1170
    user: root
    ports:
      - "8084:8084"
      - "8443:8443"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - LANG=es_AR.UTF-8
      - NIFI_JVM_HEAP_MAX=2048m
      - NIFI_JVM_DEBUGGER=DEBUG
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=012345678912
    volumes:
      - ../../Librerias/:/home/nifi/
      - ./conf/:/opt/nifi/nifi-1.17.0/conf/
      - ./content_repository/:/opt/nifi/nifi-1.17.0/content_repository/
      - ./database_repository/:/opt/nifi/nifi-current/database_repository/
      - ./flowfile_repository/:/opt/nifi/nifi-current/flowfile_repository/
      - ./provenance_repository/:/opt/nifi/nifi-1.17.0/provenance_repository/
      - ./logs/:/opt/nifi/nifi-1.17.0/logs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"