version: '3.8'
services:
  nifi1114:
    image: 'apache/nifi:1.11.4'
    container_name: nifi1114
    hostname: nifi1114
    user: root
    ports:
      - "8084:8084"
    environment:
      - NIFI_WEB_HTTP_PORT=8084
      - NIFI_ELECTION_MAX_WAIT=1 min
      - TZ=America/Argentina/Buenos_Aires
      - LANG=es_AR.UTF-8
      - NIFI_JVM_HEAP_MAX=2048m      
    volumes:
      - ../../Librerias/:/home/nifi/
      - ./conf/:/opt/nifi/nifi-1.11.4/conf/    
      - ./content_repository/:/opt/nifi/nifi-1.11.4/content_repository/
      - ./database_repository/:/opt/nifi/nifi-1.11.4/database_repository/
      - ./flowfile_repository/:/opt/nifi/nifi-1.11.4/flowfile_repository/
      - ./provenance_repository/:/opt/nifi/nifi-1.11.4/provenance_repository/
      - ./logs/:/opt/nifi/nifi-1.11.4/logs/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"