version: '3.8'
services:
  nifi200M4:
    image: 'apache/nifi:2.0.0-M4'
    container_name: nifi200M4
    hostname: nifi200M4
    user: root
    ports:
      - "8084:8084"
      - "9443:9443"
    environment:
      - NIFI_WEB_HTTP_PORT=8084
      - NIFI_WEB_HTTPS_PORT=9443
      - NIFI_ELECTION_MAX_WAIT=1 min
      - TZ=America/Argentina/Buenos_Aires
      - LANG=es_AR.UTF-8
      - NIFI_JVM_HEAP_MAX=2048m
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456781234
    volumes:
      - ../../Librerias/:/home/nifi/
      - ./conf/:/opt/nifi/nifi-current/conf/
      - ./content_repository/:/opt/nifi/nifi-current/content_repository/
      - ./database_repository/:/opt/nifi/nifi-current/database_repository/
      - ./flowfile_repository/:/opt/nifi/nifi-current/flowfile_repository/
      - ./provenance_repository/:/opt/nifi/nifi-current/provenance_repository/
      - ./logs/:/opt/nifi/nifi-current/logs
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"